[project]
name = "analytics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.0.0",
    "pandas>=2.0.0",
    "scikit-learn>=1.5.0",
    "joblib>=1.4.0",
    "scipy>=1.13.0",
    "seaborn>=0.13.0",
    "matplotlib>=3.8.0"
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
    "ruff>=0.13.3",
]
